SUPABASE_URL='https://dbqaixoeritjeysrebfc.supabase.co'
SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicWFpeG9lcml0amV5c3JlYmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0NzE0MTcsImV4cCI6MjAzMDA0NzQxN30.Hzq6Pf6HoBr2wLnU8P8MgC3FEzMVn-D9TpxhGLrqhOY'
OPENAI_API_KEY='sk-experiments-3dCmmJvM8Sxvc3tlb38YT3BlbkFJ22jYAny1ZlMwLJy302mI'
REPLICATE_API_TOKEN='4bc3a8f3ef27595b11bf291d41865b4e7c53f96f'
SNOWFLAKE_USER='POKHARELSRJ'
SNOWFLAKE_PASSWORD='Ax+by+cz=1'
SNOWFLAKE_ACCOUNT='uhcmwnv-vbb10105'
SNOWFLAKE_WAREHOUSE='COMPUTE_WH'